### PR TITLE
random updates

### PR DESCRIPTION
**Pull request by cconrad8**

### CODE REVIEW

**Comment by cconrad8** [comment]
@anngvu struggling with getting this to build, even though it works in codespace! 
- but I was making some updates to the docs and trying to add the alogolia search bar

**Comment by cconrad8** [comment]
oh wait yay i got it! I updated the node version in vercel...I don't totally know why this works. Now trying to figure out why the search bar doesn't work

image

**Comment by anngvu** [comment]
Well, I tested the search bar, have to read more into Algolia steps for why no results -- perhaps need to run something to process/index the pages first?

**Comment by cconrad8** [comment]
@anngvu Just forwarded you the instructions, maybe if you see something I didn't do? I also emailed them to ask

**Comment by cconrad8** [comment]
https://crawler.algolia.com/admin/crawlers/85cf5368-cf19-48b3-a950-4ae93287cf56/path-explorer

I think you should be able to see this too after I added you to the project - but this path explorer could be helpful to diagnose issues

**Comment by anngvu** [comment]
@cconrad8 I'm OK with you merging to see if the search doesn't work bc has to do with it being a preview site (?). I updated the configuration -- still probably not the most optimized -- but it seems to work at least in the test index search. 
image

**Comment by cconrad8** [comment]
Ok we can give it a shot to see. Thanks @anngvu!

**Pull request merged**
