### PR TITLE
Cconrad8 patch 1

### PR DESCRIPTION
**Pull request by cconrad8**

### CODE REVIEW

**Comment by cconrad8** [comment]
I think this is actually working now...! @anngvu

**Comment by anngvu** [comment]
I'm doing a comparison page by page, and I think overall looks good (definitely nicer presentation in some pages). **_But_**, migrations are hard, and it looks like we lost the very important [mission](https://docs.graybrcaatlas.org/#mission) and [roadmap](https://docs.graybrcaatlas.org/#roadmap) 😦. I think these are needed _**before**_ merging.

**_Optional_** suggestions here (can worry about these _after_ merging): https://github.com/gf-dcc/docs/issues/69

**Review by anngvu — CHANGES_REQUESTED** [review]
- I removed unnecessary workflows that were part of the template. 
- Need to migrate mission and roadmap currently in overview.

**Review by anngvu — APPROVED** [review]
Ready to roll (over)!

**Pull request merged**
