### PR TITLE
Update _meta.json

### PR DESCRIPTION
**Pull request by cconrad8**

### CODE REVIEW

**Comment by anngvu** [comment]
@elv-sb Added you as reviewer so you can be tie-breaker. What do you think of this new template ([Visit Preview](https://docs-git-testingchristina-gray-foundation-dcc.vercel.app/)) vs. the [current one](https://docs.graybrcaatlas.org/) in terms of information navigation/presentation? I'm leaning a little more towards [current template](https://docs.graybrcaatlas.org/), but maybe it's just because that's what I'm more used to.

**Comment by anngvu** [comment]
Also, I think we lose the "What's on this page" summary, which I think is really helpful.

**Review by anngvu — COMMENTED** [review]
Prefer to keep current template. I think we lose some hierarchical structure / features.

**Comment by brynnz22** [comment]
I agree! I like the current template.

**Comment by cconrad8** [comment]
@anngvu  I should have specified in our convo - that you can actually have a combination of all of these options 
https://nextra.site/docs/docs-theme/theme-configuration
Here's the guidelines I was using - I'm happy to stick with the original format (honestly just found it fun to play around with!)

**Comment by anngvu** [comment]
Yeah, the experimentation was still really useful to see other layout possibilities even if it didn't yield an even better combination! There does seem to be other things in the theme config that we should add... e.g. https://nextra.site/docs/docs-theme/theme-configuration#chat-link

**Pull request closed without merging**
