### PR TITLE
Merge doc website

### PR DESCRIPTION
**Pull request by cconrad8**
tested here: https://docs-8cvx.vercel.app/

### CODE REVIEW

**Comment by cconrad8** [comment]
I can't figure out the right way to preview it!

**Comment by anngvu** [comment]
@cconrad8 I think this might take some extra work to resolve...

- A lot of content not yet migrated:
  -  https://docs.graybrcaatlas.org/onboarding/onboarding-checklist
  - https://docs.graybrcaatlas.org/onboarding/data-analysis
  - https://docs.graybrcaatlas.org/onboarding/data-sharing#1-uploading-data (blank right now)
  - more...
- Workflows needing reconfiguration. I'll look into what's breaking.

I think it would be better to finish transferring content to the new layout before we merge -- more useful content/subtance vs design/layout. We can still iframe the current docs site and swap out once the workflows are fixed and content is 100% ready.

**Comment by cconrad8** [comment]
Yeah I'm wondering instead if I can just push it to this branch - staging?

**Comment by anngvu** [comment]
I think it's a file that got deleted.

**Comment by cconrad8** [comment]
ok yeah I think maybe I found it - nodule-modules for some reason got messed up when i went from my practice website to this current one. I'll test it out - thanks for finding that. and i'll stick with staging. it just seems easier for me to work with the gray foundation repo then my own personal one that doesn't have things downloaded properly

**Pull request closed without merging**
