### PR TITLE
Add cBioPortal page

### LINKED ISSUE #82: SOP for cBioPortal integration/submission
- Internal tracking: [GFP-269](https://sagebionetworks.jira.com/browse/GFP-269)
- Similar to #65

Discussed SOP today, draft to be cleaned up, @inodb and @ritikakundra can review the PR and contribute before merging.

### PR DESCRIPTION
**Pull request by anngvu**
See preview here 👉🏼  https://docs-git-feat-cbioportal-page-gf-dcc-service.vercel.app/docs/workflows/cBioPortal

@cconrad8 -- You can make any changes before adding Ino and Ritika to review. I prompted ChatGPT to simplify and create the rough diagram from original version, so there things to double-check. Restyling colors fine.

### CODE REVIEW

**Review by cconrad8 — APPROVED** [review]
looks great! I changed the colors and made some text edits.  otherwise I think good to me!

**Comment by ritikakundra** [comment]
Looks good to me. Quick question, for, " Is direct data contribution to cBioPortal feasible by the contributor?- Yes", not sure why we need "CONTRIBUTOR: Works directly with MSKCC on the submission process of data to cBioPortal".

Maybe not for the workflow, but we should figure out how you will hand over the files to us. For Drapkin cohort, if I remember correctly, it was via synapse. Should we continue with that process? Datahub will not be an option as data is not public till phase 3

**Comment by cconrad8** [comment]
Following our discussion today: We want to better streamline this process and let's try to simplify the workflow so it doesn't have as many exchanges between the contributor, MSK, and Sage. 
- Sage will prepare the files to be submitted and discuss internally on how we can use existing DCC (Genie and HTAN) protocols to prep files

**Comment by anngvu** [comment]
@ritikakundra @inodb @cconrad8 

I simplified this a bit so MSKCC does even less (no path to work directly with contribs). Merging this version, make a PR or issue if we need to revisit later.

**Pull request merged**
